FROM python:3.13.1-alpine3.21
RUN pip install --upgrade pip && mkdir -p /usr/src/app && addgroup -S worker && adduser -S worker -G worker
COPY . /usr/src/app
RUN chown -R worker:worker /usr/src/app

USER worker
WORKDIR /usr/src/app

RUN pip install --no-cache-dir -r requirements.txt

#EXPOSE 5000

# CMD [ "python", "./app.py" ]
CMD [ "sh" ]
